### PR TITLE
Readme: Show regular formatting for original readme content

### PR DESCRIPTION
**Pull request by spen**
My guess is that the closing back-ticks were left out intentionally, but that leaves the original readme content quite unpleasant to read. In case this was not intentional this PR lets the markdown formatting apply to the original content.

### CODE REVIEW

**Comment by jsnajdr** [comment]
That was certainly not intentional. Thanks for fixing @spen!

**Comment by jsnajdr** [comment]
That was certainly not intentional. Thanks for fixing @spen!

Just please merge this into the `calypso-1.6` branch, not `calypso-1.5`.

**Comment by jsnajdr** [comment]
I just pushed an one-liner to `calypso-1.6` instead of wasting time rebasing this PR. Thanks Spen for the fix anyway 👍

**Comment by spen** [comment]
Thanks for sorting @jsnajdr :) <3

**Pull request closed without merging**
